version: "2"

run:
  concurrency: 8
  go: "1.24.3"

linters:
  default: none
  enable:
    - asciicheck
    - copyloopvar
    - dupl
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - nakedret
    - nestif
    - nolintlint
    - revive
    - unused
    - whitespace

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: io/ioutil
            desc: 'Deprecated: As of Go 1.16, the same functionality is now provided by package `io` or package `os`.'
  forbidigo:
    forbid:
      - p: ^print.*$
        msg: "use logging instead of print statements"
      - p: ^fmt\.Print.*$
        msg: "use logging instead of fmt.Print statements"
    exclude-godoc-examples: true
  funlen:
    lines: 100
    statements: 80
  gocognit:
    min-complexity: 30
  gocritic:
    enabled-checks:
      - badLock
      - badRegexp
      - badSorting
      - badSyncOnceFunc
      - deferInLoop
      - dynamicFmtString
      - emptyDecl
      - filepathJoin
  gocyclo:
    min-complexity: 20
  importas:
    no-unaliased: true
    alias:
      - pkg: github.com/frankban/quicktest
        alias: qt
  lll:
    line-length: 150
  nakedret:
    max-func-lines: 2
  nestif:
    min-complexity: 6
  nolintlint:
    require-explanation: true
    require-specific: true
    allow-no-explanation:
      - errcheck
      - lll
  revive:
    severity: error
    rules:
      - name: atomic
        disabled: false
      - name: bare-return
        disabled: true # covered by nakedret linter
      - name: blank-imports
        disabled: false
      - name: bool-literal-in-expr
        disabled: false
      - name: confusing-results
        disabled: false
      - name: constant-logical-expr
        disabled: false
      - name: context-keys-type
        disabled: false
      - name: datarace
        disabled: false
      - name: deep-exit
        disabled: false
      - name: defer
        disabled: false
      - name: dot-imports
        disabled: false
      - name: duplicated-imports
        disabled: false
      - name: early-return
        disabled: false
      - name: empty-block
        disabled: false
      - name: empty-lines
        disabled: false
      - name: error-naming
        disabled: false
      - name: error-return
        disabled: false
      - name: error-strings
        disabled: true # until decided
      - name: filename-format
        arguments:
          - '^[_a-z][_a-z0-9]*.go$'
        disabled: false
      - name: flag-parameter
        disabled: false
      - name: function-result-limit
        arguments:
          - 3
        disabled: false
      - name: get-return
        disabled: false
      - name: identical-branches
        disabled: false
      - name: import-alias-naming
        arguments:
          - allowRegex: '^[a-z][a-z0-9]*$'
            denyRegex: '^v\d+$'
        disabled: false
      - name: import-shadowing
        disabled: false
      - name: increment-decrement
        disabled: false
      - name: indent-error-flow
        arguments:
          - preserveScope
        disabled: false
      - name: modifies-value-receiver
        disabled: false
      - name: optimize-operands-order
        disabled: false
      - name: range
        disabled: false
      - name: receiver-naming
        arguments:
          - maxLength: 4
        disabled: false
      - name: redefines-builtin-id
        disabled: false
      - name: redundant-import-alias
        disabled: false
      - name: string-of-int
        disabled: false
      - name: struct-tag
        disabled: false
      - name: superfluous-else
        disabled: false
      - name: time-equal
        disabled: false
      - name: unchecked-type-assertion
        arguments:
          - acceptIgnoredAssertionResult: true
        disabled: false
      - name: unconditional-recursion
        disabled: false
      - name: unexported-naming
        disabled: false
      - name: unexported-return
        disabled: false
      - name: unnecessary-stmt
        disabled: false
      - name: unreachable-code
        disabled: false
      - name: unused-parameter
        arguments:
          - allowRegex: '^_'
        disabled: true # TODO: re-enable
      - name: unused-receiver
        disabled: true # TODO: re-enable
      - name: use-any
        disabled: false
      - name: useless-break
        disabled: false
      - name: var-naming
        disabled: false
      - name: waitgroup-by-value
        disabled: false
  staticcheck:
    checks:
      - all
      - -QF1008
      - -ST1000
      - -ST1003
      - -ST1005
      - -ST1016

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - funlen
        - gocognit
        - gocritic
        - gocyclo
        - lll
        - nestif
        - dupl
      path: '_test\.go$'
    - path: '_test\.go$'
      text: 'function-result-limit:'
    - path: '_test\.go$'
      text: 'bool-literal-in-expr:'
    - path: '_test\.go$'
      text: 'unused-parameter:'
    - path: '_test\.go$'
      text: 'unchecked-type-assertion:'
    - path: 'cmd/.*\.go$'
      linters:
        - gochecknoinits
        - forbidigo
        - depguard
    - path: 'internal/.*\.go$'
      linters:
        - depguard
    - path: 'pkg/.*\.go$'
      linters:
        - depguard
