name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Build binaries
      run: |
        mkdir -p dist
        
        # Linux amd64
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/dev-postgres-mcp-linux-amd64 ./cmd/dev-postgres-mcp
        
        # Linux arm64
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o dist/dev-postgres-mcp-linux-arm64 ./cmd/dev-postgres-mcp
        
        # macOS amd64
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o dist/dev-postgres-mcp-darwin-amd64 ./cmd/dev-postgres-mcp
        
        # macOS arm64
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o dist/dev-postgres-mcp-darwin-arm64 ./cmd/dev-postgres-mcp
        
        # Windows amd64
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/dev-postgres-mcp-windows-amd64.exe ./cmd/dev-postgres-mcp

    - name: Create checksums
      run: |
        cd dist
        sha256sum * > checksums.txt

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/dev-postgres-mcp-linux-amd64
          dist/dev-postgres-mcp-linux-arm64
          dist/dev-postgres-mcp-darwin-amd64
          dist/dev-postgres-mcp-darwin-arm64
          dist/dev-postgres-mcp-windows-amd64.exe
          dist/checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
